services:
  bot:
    build: ./bot
    env_file: .env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: